// ─── MOCK DATA ────────────────────────────────────────────────────────────────
// TODO: Replace with real API calls when backend is ready.
// Each section maps to a resource in the future REST/GraphQL API.

// ─── USERS ────────────────────────────────────────────────────────────────────
export const MOCK_USERS = [
  {
    id: "u1",
    name: "Valentina López",
    email: "valentina@example.com",
    password: "123456",
    role: "client",
    avatar: "https://i.pravatar.cc/150?img=47",
    phone: "+598 91 234-5678",
    createdAt: "2024-03-15",
  },
  {
    id: "u2",
    name: "Mateo García",
    email: "mateo@example.com",
    password: "123456",
    role: "provider",
    avatar: "https://i.pravatar.cc/150?img=12",
    phone: "+598 99 876-5432",
    createdAt: "2024-01-10",
    providerId: "p1",
  },
  {
    id: "u3",
    name: "Sofía Martínez",
    email: "sofia@example.com",
    password: "123456",
    role: "client",
    avatar: "https://i.pravatar.cc/150?img=32",
    phone: "+598 95 555-1234",
    createdAt: "2024-05-20",
  },
  {
    id: "u4",
    name: "Admin TuEvento",
    email: "admin@tuevento.com.uy",
    password: "admin123",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?img=60",
    phone: "+598 00 000-0000",
    createdAt: "2024-01-01",
  },
];

// ─── CATEGORIES ───────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: "catering",        label: "Catering",         icon: "🍽️",  count: 48 },
  { id: "dj",              label: "DJ & Música",       icon: "🎧",  count: 32 },
  { id: "fotografia",      label: "Fotografía",        icon: "📷",  count: 56 },
  { id: "decoracion",      label: "Decoración",        icon: "🎀",  count: 39 },
  { id: "animacion",       label: "Animación",         icon: "🎪",  count: 24 },
  { id: "barra",           label: "Barra de Tragos",   icon: "🍹",  count: 19 },
  { id: "sonido",          label: "Sonido & Luces",    icon: "💡",  count: 28 },
  { id: "parrilla",        label: "Parrilla",          icon: "🥩",  count: 22 },
  { id: "pizza",           label: "Pizzas",            icon: "🍕",  count: 17 },
  { id: "castillo",        label: "Castillos",         icon: "🏰",  count: 14 },
  { id: "mozos",           label: "Mozos",             icon: "🤵",  count: 31 },
  { id: "video",           label: "Video & Cine",      icon: "🎬",  count: 21 },
];

// ─── PROVIDERS ────────────────────────────────────────────────────────────────
export const PROVIDERS = [
  {
    id: "p1",
    name: "Sabores del Sur Catering",
    category: "catering",
    categoryLabel: "Catering",
    rating: 4.9,
    reviewCount: 124,
    priceFrom: 45000,
    zone: "Montevideo e Interior",
    zones: ["Montevideo", "Canelones", "Maldonado", "Interior del país"],
    badges: ["verified", "top", "popular"],
    images: [
      "https://images.unsplash.com/photo-1414235077428-338989a1e434?w=800&q=80",
      "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=80",
      "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&q=80",
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
      "https://images.unsplash.com/photo-1488992783499-418eb1f62d08?w=800&q=80",
    ],
    description:
      "Catering premium para eventos de todo tipo. Más de 10 años de experiencia en bodas, cumpleaños, eventos empresariales y fiestas privadas. Utilizamos ingredientes frescos y de primera calidad.",
    longDescription:
      "Somos un equipo de chefs profesionales con más de una década en el rubro. Nos especializamos en cocina uruguaya y mediterránea, adaptándonos a cada evento. Contamos con equipamiento propio, mozos incluidos en todos los paquetes y atención personalizada desde el primer contacto.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 45000,
        priceUnit: "por persona",
        description: "Ideal para eventos íntimos de hasta 50 personas.",
        includes: [
          "Entrada fría (fiambres y quesos)",
          "Plato principal a elección (2 opciones)",
          "Postre",
          "Mozos incluidos",
          "Vajilla y mantelería",
        ],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 65000,
        priceUnit: "por persona",
        description: "La opción más elegida para eventos de 50 a 150 personas.",
        includes: [
          "Entrada fría + caliente",
          "Plato principal (3 opciones)",
          "Guarniciones variadas",
          "Postre y torta de cumpleaños",
          "Servicio de mozos premium",
          "Vajilla, mantelería y decoración de mesa",
          "Coordinador de servicio",
        ],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 95000,
        priceUnit: "por persona",
        description: "Experiencia gastronómica completa para hasta 300 personas.",
        includes: [
          "Cóctel de bienvenida",
          "Entrada fría y caliente gourmet",
          "Plato principal (5 opciones + vegetariano)",
          "Estación de quesos y fiambres",
          "Postre buffet + torta personalizada",
          "Mozos en uniforme de gala",
          "Vajilla de porcelana y cristalería",
          "Coordinador y maitre",
          "Armado y desarmado incluido",
        ],
      },
    ],
    extras: [
      { id: "e1", name: "Torta personalizada", price: 18000 },
      { id: "e2", name: "Servicio de bebidas alcohólicas", price: 12000, priceUnit: "por persona" },
      { id: "e3", name: "Mozo adicional", price: 25000 },
      { id: "e4", name: "Estación de café", price: 8000 },
    ],
    eventTypes: ["Cumpleaños", "Casamiento", "Empresarial", "Fiesta privada"],
    cancellationPolicy:
      "Cancelación gratuita hasta 15 días antes del evento. Después de esa fecha se retiene el 50% de la seña.",
    faq: [
      { q: "¿Incluyen los mozos?", a: "Sí, todos los paquetes incluyen mozos profesionales." },
      { q: "¿Trabajan fuera de Montevideo?", a: "Sí, cubrimos todo el interior con un pequeño recargo por traslado." },
      { q: "¿Tienen opciones vegetarianas?", a: "Sí, siempre adaptamos el menú a las necesidades dietéticas." },
    ],
    reviews: [
      { id: "r1", author: "Camila R.", avatar: "https://i.pravatar.cc/60?img=25", rating: 5, date: "12 may 2025", text: "Increíble servicio, todos los invitados quedaron encantados con la comida. Los mozos fueron muy profesionales." },
      { id: "r2", author: "Pablo M.", avatar: "https://i.pravatar.cc/60?img=11", rating: 5, date: "3 abr 2025", text: "Los contratamos para el cumple de 15 de mi hija y fue todo perfecto. Superaron las expectativas." },
      { id: "r3", author: "Laura V.", avatar: "https://i.pravatar.cc/60?img=35", rating: 4, date: "22 mar 2025", text: "Muy buen servicio. La comida estuvo excelente, solo hubo una pequeña demora al inicio pero lo resolvieron rápido." },
    ],
    responseTime: "Responde en ~2 hs",
    verified: true,
    totalBookings: 320,
    owner: { name: "Mateo García", phone: "+598 99 876-5432" },
  },
  {
    id: "p2",
    name: "DJ Nico Soundstorm",
    category: "dj",
    categoryLabel: "DJ & Música",
    rating: 4.8,
    reviewCount: 87,
    priceFrom: 35000,
    zone: "Montevideo",
    zones: ["Montevideo", "Canelones"],
    badges: ["verified", "fast"],
    images: [
      "https://images.unsplash.com/photo-1571903347406-d0d1b1f08e82?w=800&q=80",
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    ],
    description:
      "DJ profesional con más de 8 años de experiencia en fiestas, casamientos y eventos corporativos. Equipos propios de última generación.",
    longDescription:
      "Nicolás Rodríguez es DJ profesional con residencia en múltiples locales de Montevideo. Se especializa en música electrónica, latina y pop, adaptando el set a cada tipo de evento. Cuenta con equipos Pioneer de última generación y sistema de luces profesional.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 35000,
        priceUnit: "por evento",
        description: "3 horas de música en vivo.",
        includes: ["3 horas de DJ set", "Equipo de sonido básico", "Playlist personalizada"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 55000,
        priceUnit: "por evento",
        description: "5 horas con iluminación incluida.",
        includes: ["5 horas de DJ set", "Sistema de sonido profesional", "Luces básicas (par LED)", "Playlist personalizada + consulta previa"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 85000,
        priceUnit: "por evento",
        description: "Noche completa con show de luces.",
        includes: ["6+ horas de DJ set", "Sistema de sonido premium", "Show de luces completo (moving heads, laser, humo)", "Pantalla LED incluida", "MC opcional"],
      },
    ],
    extras: [
      { id: "e1", name: "Hora extra", price: 12000 },
      { id: "e2", name: "Sistema de luces adicional", price: 15000 },
      { id: "e3", name: "Pantalla LED", price: 20000 },
    ],
    eventTypes: ["Cumpleaños", "Casamiento", "Fiesta privada", "Empresarial"],
    cancellationPolicy: "Cancelación gratuita hasta 7 días antes. Seña no reembolsable pasada esa fecha.",
    faq: [
      { q: "¿Traés el equipo vos?", a: "Sí, todo el equipamiento es propio. Solo necesito una toma de corriente." },
      { q: "¿Aceptás pedidos de canciones?", a: "Por supuesto, es parte del servicio. Podés enviarme una lista previa." },
    ],
    reviews: [
      { id: "r1", author: "Tomás F.", avatar: "https://i.pravatar.cc/60?img=8", rating: 5, date: "5 jun 2025", text: "Nico es un crack. Puso la fiesta a tope toda la noche. 100% lo recomiendo." },
      { id: "r2", author: "Abril S.", avatar: "https://i.pravatar.cc/60?img=42", rating: 5, date: "20 may 2025", text: "Estuvo genial en mi cumple de 30. Conoce de música y le pone mucha onda." },
    ],
    responseTime: "Responde en ~1 hs",
    verified: true,
    totalBookings: 210,
    owner: { name: "Nicolás Rodríguez", phone: "+598 94 444-5555" },
  },
  {
    id: "p3",
    name: "Luz & Arte Fotografía",
    category: "fotografia",
    categoryLabel: "Fotografía",
    rating: 5.0,
    reviewCount: 203,
    priceFrom: 60000,
    zone: "Montevideo e Interior",
    zones: ["Montevideo", "Canelones", "Maldonado", "Interior del país"],
    badges: ["verified", "top", "popular"],
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
      "https://images.unsplash.com/photo-1519741497674-611c71ddc95b?w=800&q=80",
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80",
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80",
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
    ],
    description:
      "Fotografía y video profesional para eventos. Capturamos cada momento especial con un estilo moderno y natural.",
    longDescription:
      "Equipo de fotógrafos y videocineastas especializados en eventos sociales y corporativos. Usamos equipamiento Sony full-frame y editamos con Lightroom y Premiere. Entregamos galería digital, prints y video highlights.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 60000,
        priceUnit: "por evento",
        description: "Fotografía durante 4 horas.",
        includes: ["4 horas de cobertura", "1 fotógrafo", "200 fotos editadas", "Galería digital privada"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 95000,
        priceUnit: "por evento",
        description: "Foto + video highlights.",
        includes: ["6 horas de cobertura", "1 fotógrafo + asistente", "400 fotos editadas", "Video highlights 3 min", "Galería digital + USB"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 160000,
        priceUnit: "por evento",
        description: "Cobertura completa foto + video cinematográfico.",
        includes: ["Cobertura completa (apertura - cierre)", "2 fotógrafos + videógrafo", "600+ fotos editadas", "Video cinematográfico 8 min + teaser 1 min", "Álbum físico premium 30x30", "Galería digital + USB + impresiones seleccionadas"],
      },
    ],
    extras: [
      { id: "e1", name: "Hora adicional", price: 18000 },
      { id: "e2", name: "Álbum físico extra", price: 35000 },
      { id: "e3", name: "Drone (aerial shots)", price: 25000 },
      { id: "e4", name: "Booth fotográfico", price: 40000 },
    ],
    eventTypes: ["Cumpleaños", "Casamiento", "Empresarial", "Infantil", "Fiesta privada"],
    cancellationPolicy: "Cancelación gratuita hasta 30 días antes. Después se retiene el 30% de la seña.",
    faq: [
      { q: "¿En cuánto tiempo entregan las fotos?", a: "En 2-3 semanas después del evento." },
      { q: "¿Viajan al interior?", a: "Sí, con un recargo por traslado y alojamiento." },
    ],
    reviews: [
      { id: "r1", author: "Florencia B.", avatar: "https://i.pravatar.cc/60?img=28", rating: 5, date: "10 jun 2025", text: "Las fotos de mi casamiento son una obra de arte. Capturaron cada momento de manera mágica." },
      { id: "r2", author: "Julián C.", avatar: "https://i.pravatar.cc/60?img=15", rating: 5, date: "2 jun 2025", text: "Profesionales y creativos. El video highlights nos hizo llorar de emoción." },
      { id: "r3", author: "Natalia P.", avatar: "https://i.pravatar.cc/60?img=51", rating: 5, date: "18 may 2025", text: "Excelente trabajo. Muy atentos, discretos durante el evento y el resultado superó lo esperado." },
    ],
    responseTime: "Responde en ~3 hs",
    verified: true,
    totalBookings: 485,
    owner: { name: "Luciana Torres", phone: "+598 97 777-8888" },
  },
  {
    id: "p4",
    name: "Barra Móvil Cocktail Co.",
    category: "barra",
    categoryLabel: "Barra de Tragos",
    rating: 4.7,
    reviewCount: 65,
    priceFrom: 30000,
    zone: "Montevideo y Canelones",
    zones: ["Montevideo", "Canelones"],
    badges: ["verified", "fast"],
    images: [
      "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80",
      "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80",
      "https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=800&q=80",
      "https://images.unsplash.com/photo-1532634922-8fe0b757fb13?w=800&q=80",
    ],
    description:
      "Barra de tragos artesanales para eventos. Bartenders profesionales, cócteles creativos y presentación impecable.",
    longDescription:
      "Cocktail Co. ofrece barras móviles con bartenders certificados, licores premium y una presentación visual espectacular. Ideales para casamientos, cumpleaños y eventos corporativos. Incluyen show de flair bartending a pedido.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 30000,
        priceUnit: "por evento",
        description: "Barra estándar por 3 horas.",
        includes: ["1 bartender", "3 horas de servicio", "5 cócteles de carta", "Barra plegable incluida"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 50000,
        priceUnit: "por evento",
        description: "Barra premium por 5 horas con show.",
        includes: ["2 bartenders", "5 horas de servicio", "10 cócteles de carta + 2 especiales del evento", "Show de flair", "Barra iluminada", "Vasos y cristalería"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 75000,
        priceUnit: "por evento",
        description: "Barra open bar de noche completa.",
        includes: ["3 bartenders + asistente", "Noche completa", "Open bar (destilados, vinos, cervezas)", "Barra backlit personalizada", "Cócteles ilimitados de carta", "Mocktails para no alcohólicos", "Show de flair + personalización del evento"],
      },
    ],
    extras: [
      { id: "e1", name: "Hora extra", price: 8000 },
      { id: "e2", name: "Personalización de vasos", price: 5000 },
      { id: "e3", name: "Show de flair adicional", price: 10000 },
    ],
    eventTypes: ["Cumpleaños", "Casamiento", "Empresarial", "Fiesta privada"],
    cancellationPolicy: "Cancelación gratuita hasta 10 días antes.",
    faq: [
      { q: "¿Traen los licores?", a: "Sí, los paquetes incluyen todos los ingredientes. Solo necesitamos acceso a agua y electricidad." },
    ],
    reviews: [
      { id: "r1", author: "Ignacio T.", avatar: "https://i.pravatar.cc/60?img=7", rating: 5, date: "25 may 2025", text: "La barra fue lo mejor de la fiesta. Los tragos eran increíbles y el bartender un showman total." },
    ],
    responseTime: "Responde en ~30 min",
    verified: true,
    totalBookings: 156,
    owner: { name: "Ramiro Vega", phone: "+598 92 222-3333" },
  },
  {
    id: "p5",
    name: "Decoraciones Mágicas",
    category: "decoracion",
    categoryLabel: "Decoración",
    rating: 4.6,
    reviewCount: 91,
    priceFrom: 25000,
    zone: "Montevideo e Interior",
    zones: ["Montevideo", "Canelones", "Maldonado"],
    badges: ["verified"],
    images: [
      "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800&q=80",
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
      "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=800&q=80",
    ],
    description:
      "Decoración temática y personalizada para todo tipo de eventos. Globos, flores, centros de mesa y ambientación completa.",
    longDescription:
      "Somos especialistas en crear ambientes únicos para cada celebración. Desde decoraciones infantiles coloridas hasta montajes elegantes para casamientos. Cada trabajo es personalizado según el estilo y presupuesto del cliente.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 25000,
        priceUnit: "por evento",
        description: "Decoración temática para hasta 30 personas.",
        includes: ["Arco de globos", "Centros de mesa (5 unidades)", "Cartel personalizado", "Armado y desarmado"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 45000,
        priceUnit: "por evento",
        description: "Decoración completa para hasta 80 personas.",
        includes: ["2 arcos de globos", "Centros de mesa (10 unidades)", "Mesa dulce decorada", "Cartel LED", "Guirnaldas y luces", "Armado y desarmado"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 80000,
        priceUnit: "por evento",
        description: "Ambientación total para hasta 200 personas.",
        includes: ["Decoración integral del salón", "Mesa de honor decorada", "Mesa dulce premium", "Iluminación ambiental", "Flores frescas", "Cartel neon personalizado", "Photocall/backdrop", "Coordinador de decoración"],
      },
    ],
    extras: [
      { id: "e1", name: "Mesa dulce", price: 15000 },
      { id: "e2", name: "Cartel neon", price: 20000 },
      { id: "e3", name: "Flores frescas", price: 12000 },
    ],
    eventTypes: ["Cumpleaños", "Casamiento", "Infantil", "Fiesta privada"],
    cancellationPolicy: "Cancelación gratuita hasta 7 días antes. Material personalizado no reembolsable.",
    faq: [
      { q: "¿Hacen entregas fuera de Montevideo?", a: "Sí, con recargo por traslado según la zona." },
    ],
    reviews: [
      { id: "r1", author: "Carina H.", avatar: "https://i.pravatar.cc/60?img=38", rating: 5, date: "15 may 2025", text: "El salón quedó de revista. Las decoraciones eran exactamente lo que pedí, un trabajo impecable." },
      { id: "r2", author: "Diego A.", avatar: "https://i.pravatar.cc/60?img=20", rating: 4, date: "8 may 2025", text: "Muy buena calidad. Llegaron tarde al armado pero terminaron a tiempo." },
    ],
    responseTime: "Responde en ~4 hs",
    verified: true,
    totalBookings: 210,
    owner: { name: "Marcela Ríos", phone: "+598 96 666-7777" },
  },
  {
    id: "p6",
    name: "Parrilla Don Rubén",
    category: "parrilla",
    categoryLabel: "Parrilla",
    rating: 4.8,
    reviewCount: 145,
    priceFrom: 30000,
    zone: "Interior",
    zones: ["Canelones", "Maldonado", "Interior del país"],
    badges: ["verified", "popular"],
    images: [
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
      "https://images.unsplash.com/photo-1432139509613-5c4255815697?w=800&q=80",
    ],
    description:
      "Asado y parrilla profesional para eventos. Carnes de primera calidad, cortes especiales y el verdadero sabor uruguayo.",
    longDescription:
      "Rubén Gómez y su equipo llevan más de 15 años haciendo asados para eventos de todo tipo. Trabajamos con carnes de primera selección de frigoríficos premium. Todo el equipamiento es nuestro.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 30000,
        priceUnit: "por persona",
        description: "Asado completo hasta 30 personas.",
        includes: ["Asado clásico (vacío, chorizo, morcilla)", "Ensaladas", "Pan", "Parrillero"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 45000,
        priceUnit: "por persona",
        description: "Parrillada premium hasta 80 personas.",
        includes: ["Parrillada variada (costilla, vacío, pollo, achuras)", "Ensaladas variadas", "Pan artesanal", "Guarniciones", "2 parrilleros"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 65000,
        priceUnit: "por persona",
        description: "Experiencia gourmet para hasta 200 personas.",
        includes: ["Cortes especiales (ojo de bife, lomo, entraña)", "Estación de embutidos artesanales", "Ensaladas gourmet", "Pan artesanal + focaccia", "Guarniciones premium", "3 parrilleros + asistente"],
      },
    ],
    extras: [
      { id: "e1", name: "Lechón asado", price: 25000 },
      { id: "e2", name: "Cordero patagónico", price: 35000 },
    ],
    eventTypes: ["Cumpleaños", "Empresarial", "Fiesta privada"],
    cancellationPolicy: "Cancelación gratuita hasta 5 días antes.",
    faq: [
      { q: "¿Necesitan espacio al aire libre?", a: "Sí, necesitamos espacio exterior o salón con extractor para la parrilla." },
    ],
    reviews: [
      { id: "r1", author: "Roberto P.", avatar: "https://i.pravatar.cc/60?img=3", rating: 5, date: "1 jun 2025", text: "El mejor asado que comí en años. Rubén es un maestro del fuego. Los invitados no paraban de pedir más." },
    ],
    responseTime: "Responde en ~2 hs",
    verified: true,
    totalBookings: 380,
    owner: { name: "Rubén Gómez", phone: "+598 91 111-2222" },
  },
  {
    id: "p7",
    name: "Animá tu Fiesta",
    category: "animacion",
    categoryLabel: "Animación",
    rating: 4.9,
    reviewCount: 78,
    priceFrom: 20000,
    zone: "Montevideo e Interior",
    zones: ["Montevideo", "Canelones", "Maldonado", "Interior del país"],
    badges: ["verified", "fast"],
    images: [
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80",
    ],
    description:
      "Animadores y recreadores para fiestas infantiles y eventos familiares. Personajes, juegos, y mucha diversión garantizada.",
    longDescription:
      "Nuestro equipo de animadores está entrenado para crear momentos mágicos. Ofrecemos personajes animados, shows de magia, karaoke, juegos grupales y mucho más. Siempre puntuales y con mucha energía.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 20000,
        priceUnit: "por evento",
        description: "2 horas de animación.",
        includes: ["2 animadores", "2 hs de show", "Juegos grupales", "Sorpresas para el homenajeado"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 35000,
        priceUnit: "por evento",
        description: "3 horas con personaje temático.",
        includes: ["3 animadores", "3 hs de show", "Personaje temático a elección", "Show de magia", "Juegos y actividades", "Foto con el personaje"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 60000,
        priceUnit: "por evento",
        description: "Fiesta temática completa.",
        includes: ["4 animadores + personaje", "4+ horas de show", "Show de magia y globoflexia", "Karaoke para niños", "Actividades para adultos", "Sorpresas personalizadas", "Coordinador de festejo"],
      },
    ],
    extras: [
      { id: "e1", name: "Hora extra", price: 8000 },
      { id: "e2", name: "Personaje adicional", price: 12000 },
      { id: "e3", name: "Pinta caritas", price: 5000 },
    ],
    eventTypes: ["Infantil", "Cumpleaños", "Fiesta privada"],
    cancellationPolicy: "Cancelación gratuita hasta 48 horas antes.",
    faq: [
      { q: "¿Qué personajes tienen?", a: "Tenemos más de 30 personajes entre princesas, superhéroes, dinosaurios y más." },
    ],
    reviews: [
      { id: "r1", author: "Andrea M.", avatar: "https://i.pravatar.cc/60?img=44", rating: 5, date: "8 jun 2025", text: "Los chicos la pasaron increíble. Los animadores fueron muy profesionales y los nenes no se aburrieron ni un minuto." },
    ],
    responseTime: "Responde en ~1 hs",
    verified: true,
    totalBookings: 195,
    owner: { name: "Lucía Fernández", phone: "+598 95 555-6666" },
  },
  {
    id: "p8",
    name: "Pizza Express Eventos",
    category: "pizza",
    categoryLabel: "Pizzas",
    rating: 4.5,
    reviewCount: 53,
    priceFrom: 18000,
    zone: "Montevideo",
    zones: ["Montevideo"],
    badges: ["fast"],
    images: [
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    ],
    description:
      "Pizzería móvil para eventos. Horno a leña, masa artesanal y sabores únicos que sorprenderán a tus invitados.",
    longDescription:
      "Llegamos con nuestro horno a leña móvil para preparar pizzas en el momento. Un show gastronómico que deleita a todos los invitados. Masa madre artesanal, ingredientes frescos y sabores únicos.",
    packages: [
      {
        id: "pk1",
        name: "Básico",
        price: 18000,
        priceUnit: "por hora",
        description: "Pizzas por hora para hasta 30 personas.",
        includes: ["Horno a leña", "3 variedades de pizza", "1 pizzero"],
      },
      {
        id: "pk2",
        name: "Estándar",
        price: 30000,
        priceUnit: "por hora",
        description: "Pizza libre por 2 horas.",
        includes: ["Horno a leña", "6 variedades de pizza", "Pizza libre por 2 hs", "2 pizzeros"],
        popular: true,
      },
      {
        id: "pk3",
        name: "Premium",
        price: 55000,
        priceUnit: "por evento",
        description: "Noche de pizza con show gastronómico.",
        includes: ["Horno a leña + horno eléctrico", "Más de 10 variedades incluyendo gourmet", "Pizza libre toda la noche", "Show de preparación en vivo", "3 pizzeros"],
      },
    ],
    extras: [
      { id: "e1", name: "Empanadas (docena)", price: 3500 },
      { id: "e2", name: "Focaccia artesanal", price: 2800 },
    ],
    eventTypes: ["Cumpleaños", "Empresarial", "Fiesta privada"],
    cancellationPolicy: "Cancelación gratuita hasta 48 horas antes.",
    faq: [{ q: "¿Tienen opciones sin TACC?", a: "Sí, ofrecemos masa sin gluten con 48 hs de anticipación." }],
    reviews: [
      { id: "r1", author: "Sebastián K.", avatar: "https://i.pravatar.cc/60?img=6", rating: 4, date: "30 may 2025", text: "Las pizzas estaban riquísimas y el show del horno a leña fue un hit." },
    ],
    responseTime: "Responde en ~45 min",
    verified: false,
    totalBookings: 120,
    owner: { name: "Carlos Benítez", phone: "+598 93 333-4444" },
  },
];

// ─── RESERVATIONS ─────────────────────────────────────────────────────────────
export const MOCK_RESERVATIONS = [
  {
    id: "res1",
    clientId: "u1",
    providerId: "p1",
    providerName: "Sabores del Sur Catering",
    providerCategory: "Catering",
    providerImage: "https://images.unsplash.com/photo-1414235077428-338989a1e434?w=200&q=80",
    package: "Estándar",
    extras: ["Torta personalizada"],
    date: "2025-08-15",
    time: "20:00",
    location: "Salón Crystal, Montevideo",
    eventType: "Cumpleaños",
    guests: 80,
    status: "confirmed",
    totalEstimated: 5200000,
    depositAmount: 1040000,
    depositPaid: true,
    message: "Es el cumple de 30 de mi esposa. Necesito menú sin gluten para 5 personas.",
    createdAt: "2025-06-20",
    requestNumber: "TE-2025-001",
  },
  {
    id: "res2",
    clientId: "u1",
    providerId: "p2",
    providerName: "DJ Nico Soundstorm",
    providerCategory: "DJ & Música",
    providerImage: "https://images.unsplash.com/photo-1571903347406-d0d1b1f08e82?w=200&q=80",
    package: "Premium",
    extras: ["Sistema de luces adicional"],
    date: "2025-08-15",
    time: "21:00",
    location: "Salón Crystal, Montevideo",
    eventType: "Cumpleaños",
    guests: 80,
    status: "pending",
    totalEstimated: 85000,
    depositAmount: 0,
    depositPaid: false,
    message: "Para el mismo evento que el catering. Necesitamos playlist especial años 90/2000.",
    createdAt: "2025-06-21",
    requestNumber: "TE-2025-002",
  },
  {
    id: "res3",
    clientId: "u1",
    providerId: "p3",
    providerName: "Luz & Arte Fotografía",
    providerCategory: "Fotografía",
    providerImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=200&q=80",
    package: "Estándar",
    extras: [],
    date: "2025-07-04",
    time: "18:00",
    location: "Jardín de la casa, Canelones",
    eventType: "Casamiento",
    guests: 120,
    status: "completed",
    totalEstimated: 95000,
    depositAmount: 28500,
    depositPaid: true,
    message: "Casamiento civil + fiesta. Queremos estilo fotojournalismo.",
    createdAt: "2025-05-10",
    requestNumber: "TE-2025-003",
  },
  {
    id: "res4",
    clientId: "u1",
    providerId: "p5",
    providerName: "Decoraciones Mágicas",
    providerCategory: "Decoración",
    providerImage: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=200&q=80",
    package: "Básico",
    extras: ["Cartel neon"],
    date: "2025-09-10",
    time: "16:00",
    location: "Casa particular, Maldonado",
    eventType: "Infantil",
    guests: 30,
    status: "rejected",
    totalEstimated: 45000,
    depositAmount: 0,
    depositPaid: false,
    message: "Temática de dinosaurios para cumpleaños de 5 años.",
    createdAt: "2025-06-22",
    requestNumber: "TE-2025-004",
    rejectionReason: "No tenemos disponibilidad para esa fecha.",
  },
];

// ─── PROVIDER DASHBOARD MOCK DATA ─────────────────────────────────────────────
export const PROVIDER_STATS = {
  newRequests: 8,
  confirmedBookings: 23,
  estimatedRevenue: 1840000,
  avgRating: 4.9,
  totalReviews: 124,
  responseRate: 98,
  monthlyBookings: [12, 18, 23, 31, 28, 35, 29, 40, 38, 44, 41, 48],
  monthlyRevenue: [540000, 810000, 1035000, 1395000, 1260000, 1575000],
};

export const PROVIDER_REQUESTS = [
  {
    id: "req1",
    clientName: "Valentina López",
    clientAvatar: "https://i.pravatar.cc/60?img=47",
    package: "Premium",
    eventType: "Casamiento",
    date: "2025-09-20",
    time: "19:00",
    location: "Salón Los Álamos, Canelones",
    guests: 150,
    message: "Boda de 150 personas, menú sin TACC para varios invitados.",
    status: "pending",
    estimatedTotal: 14250000,
    createdAt: "2025-06-24",
    requestNumber: "TE-2025-010",
  },
  {
    id: "req2",
    clientName: "Martín Sosa",
    clientAvatar: "https://i.pravatar.cc/60?img=18",
    package: "Estándar",
    eventType: "Empresarial",
    date: "2025-07-28",
    time: "12:00",
    location: "Oficinas Torre Libertad, Montevideo",
    guests: 60,
    message: "Almuerzo corporativo, necesitamos opciones vegetarianas.",
    status: "pending",
    estimatedTotal: 3900000,
    createdAt: "2025-06-23",
    requestNumber: "TE-2025-009",
  },
  {
    id: "req3",
    clientName: "Paula Herrero",
    clientAvatar: "https://i.pravatar.cc/60?img=56",
    package: "Básico",
    eventType: "Cumpleaños",
    date: "2025-07-12",
    time: "20:00",
    location: "Casa particular, Montevideo",
    guests: 40,
    message: "Cumple de 50, ambiente íntimo y familiar.",
    status: "confirmed",
    estimatedTotal: 1800000,
    createdAt: "2025-06-18",
    requestNumber: "TE-2025-008",
  },
];

// ─── HELPER: get provider by id ───────────────────────────────────────────────
export function getProviderById(id) {
  return PROVIDERS.find((p) => p.id === id) || null;
}

// ─── HELPER: filter providers ─────────────────────────────────────────────────
export function filterProviders({ category, zone, minPrice, maxPrice, minRating, eventType, verified, search }) {
  return PROVIDERS.filter((p) => {
    if (category && p.category !== category) return false;
    if (zone && !p.zones.some((z) => z.toLowerCase().includes(zone.toLowerCase()))) return false;
    if (minPrice && p.priceFrom < minPrice) return false;
    if (maxPrice && p.priceFrom > maxPrice) return false;
    if (minRating && p.rating < minRating) return false;
    if (eventType && !p.eventTypes.includes(eventType)) return false;
    if (verified && !p.verified) return false;
    if (search) {
      const s = search.toLowerCase();
      if (!p.name.toLowerCase().includes(s) && !p.categoryLabel.toLowerCase().includes(s) && !p.description.toLowerCase().includes(s)) return false;
    }
    return true;
  });
}
